version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d/
      - ./index.html:/usr/share/nginx/html/index.html
      - ./home/jonilson/:/home/jonilson/
    ports:
      - 8080:80
      - 8077:8077
    depends_on:
      - php
    networks:
      - server-network

  php:
    image: php:7.4-fpm-alpine3.14
    container_name: php
    command: php -S 0.0.0.0:8000 /app/index.php
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - server-network

networks:
  server-network: